#!/usr/bin/env bash

CUR_DIR=`cd $(dirname $0);pwd`

if [[ "$MSYSTEM" == "MINGW64" ]]; then
  APP_NAME=`find $CUR_DIR -maxdepth 1 -name "*.exe"`
  if [[ ${#APP_NAME} != 0 ]]; then
    for l in `ldd $APP_NAME | grep mingw | sed "s/=.*//g"`; do
      if [[ ${#l} != 0 ]]; then
        cp -u -p "/mingw64/bin/$l" "$CUR_DIR/"
        cp -u -p "/mingw64/bin/gdbus.exe"  "$CUR_DIR/"
      fi
    done
    echo -e "\033[32mDone.\033[0m"
  else
    echo -e "\033[31mWarning: *.exe executables are not found in the current directory. Please copy the distribution tool to the application directory.\033[0m"
  fi
else
  echo -e "\033[31mError: Distribution tools need to be used in the MSYS MINGW64 environment.\033[0m"
fi